---
- hosts: Dev[2]
  become: true
  vars_files:
    - vars.yml

  tasks:
  - name: make directory
    file:
      path: "/home/ec2-user/.ssh"
      state: directory
  - name: create empty file
    file:
      path: "/home/ec2-user/.ssh/authorized_keys"
      state: touch
  - name: put pubkey
    lineinfile:
      path: "/home/ec2-user/.ssh/authorized_keys"
      line: "your id_rsa.pub"
