---
- name: This is an ansible playbook roles
  hosts: Dev[1]
  become: yes
  gather_facts: no

  roles:

#   - /home/ansible/ansible-roles/upgrade-packages
#   - /home/ansible/ansible-roles/firewalld
    - tomcat/
#   - /home/ansible/ansible-roles/terraform
#   - /home/ansible/ansible-roles/jenkins
#   - /home/ansible/ansible-roles/maven
